name: Failure Protection Example

on:
  push:
    branches: [staging]

jobs:
  build-with-failure-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Build Number
        id: build_number
        uses: moonshot-partners/build-number-manager@v1
        with:
          id: staging-branch
          initial_number: 20
          gh_repo: moonshot-partners/build-numbers

      - name: Show Build Number
        run: |
          echo "🏗️ Building with number: ${{ steps.build_number.outputs.build_number }}"
          echo "📊 Previous number was: ${{ steps.build_number.outputs.previous_number }}"

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          # npm install

      - name: Run Tests
        run: |
          echo "Running tests..."
          # npm test
          # If this step fails, build number won't be incremented

      - name: Build Application
        run: |
          echo "Building application with build number ${{ steps.build_number.outputs.build_number }}"
          # npm run build
          # If this step fails, build number won't be incremented

      - name: Deploy to Staging
        run: |
          echo "Deploying build ${{ steps.build_number.outputs.build_number }} to staging"
          # kubectl apply -f k8s/staging/
          # If this step fails, build number won't be incremented

      # 🎯 IMPORTANT: The build number is only saved to the repository 
      # if ALL the above steps complete successfully!
      
      # If any step fails:
      # - The workflow stops
      # - The post action doesn't run
      # - The build number remains unchanged in the repo
      # - Next run will use the same number again

  demonstrate-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Build Number
        id: build_number
        uses: moonshot-partners/build-number-manager@v1
        with:
          id: demo-failure
          initial_number: 1
          gh_repo: moonshot-partners/build-numbers

      - name: Show Build Number
        run: |
          echo "🏗️ This build will use number: ${{ steps.build_number.outputs.build_number }}"

      - name: Simulate Build Success
        run: |
          echo "✅ Build step succeeded"

      - name: Simulate Failure
        run: |
          echo "❌ This step will fail"
          exit 1
          # Because this step fails, the build number won't be saved

      - name: This step won't run
        run: |
          echo "This won't execute because previous step failed"

      # Result: The build number for 'demo-failure' will remain unchanged
      # Next run will get the same number again 
